# Default values for otf-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: leg100/otf-agent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.2.3"

# see https://docs.otf.ninja/latest/config/flags/ for all options
env:
  # the agent token created in the OTF server instance. Must match with the one in the OTF server instance. The value used here is only for testing purposes
  OTF_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTgxNDkxMTAsImtpbmQiOiJhZ2VudF90b2tlbiIsIm9yZ2FuaXphdGlvbiI6ImN5bmtyYSIsInN1YiI6ImF0LUdiYVBldFVZNDZVQjB3dzgifQ.-4nZYNm0x1F6Q-9eNUrmMY_WceRsYbhRq3LkQGyRzJw"
  # the URL of the OTF server instance
  OTF_ADDRESS: ""
  # how many runs each agent runs in parallel
  OTF_CONCURRENCY: "1"
  # logging format
  OTF_LOG_FORMAT: "default"
  # Terraform plugin cache
  OTF_PLUGIN_CACHE: "false"
  # verbosity level
  OTF_V: "0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

topologySpreadConstraints: []
