name: Release Chart

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  release_helper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker-practice/actions-setup-docker@master
      - name: Run
        uses: addnab/docker-run-action@v3
        env:
          PLUGIN_RELEASE_BRANCH: "${{ github.event.repository.default_branch }}"
          CI_FORGE_TYPE: github
          PLUGIN_GIT_EMAIL: patrick.schratz@gmail.com
          PLUGIN_GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PLUGIN_EVENT_TYPE: "${{ github.event_name }}"
          PLUGIN_COMMIT_MESSAGE: "${{ github.event.head_commit.message }}"
          PLUGIN_REPO_OWNER: "${{ github.repository_owner }}"
          PLUGIN_REPO_NAME: "${{ github.event.repository.name }}"
          GITHUB_REPOSITORY: "${{ github.repository }}"
          isCI: "true"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          image: woodpeckerci/plugin-ready-release-go
          options: -v ${{ github.workspace }}:/app/work -e PLUGIN_RELEASE_BRANCH -e CI_FORGE_TYPE -e PLUGIN_GIT_EMAIL -e PLUGIN_GITHUB_TOKEN -e PLUGIN_EVENT_TYPE -e PLUGIN_COMMIT_MESSAGE -e isCI -e PLUGIN_REPO_OWNER -e PLUGIN_REPO_NAME -e GITHUB_REPOSITORY -e GITHUB_TOKEN
          run: |
           cd /app/work && ls -la && /app/node_modules/.bin/tsx /app/src/index.ts
