name: Release Chart

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  release_helper:
    runs-on: ubuntu-latest
    container: woodpeckerci/plugin-ready-release-go
    steps:
      - uses: actions/checkout@v4
      - name: Run
        env:
          PLUGIN_RELEASE_BRANCH: "${{ github.event.repository.default_branch }}"
          CI_FORGE_TYPE: github
          PLUGIN_GIT_EMAIL: patrick.schratz@gmail.com
          PLUGIN_GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PLUGIN_EVENT_TYPE: "${{ github.event_name }}"
          PLUGIN_COMMIT_MESSAGE: "${{ github.event.head_commit.message }}"
          PLUGIN_REPO_OWNER: "${{ github.repository_owner }}"
          PLUGIN_REPO_NAME: "${{ github.event.repository.name }}"
          GITHUB_REPOSITORY: "${{ github.repository }}"
          isCI: "true"
        run: |
          pwd
          ls -la
          which git
          git config --global --add safe.directory /__w/otf-agent-helm/otf-agent-helm
          git status
          /app/node_modules/.bin/tsx /app/src/index.ts
