on:
  workflow_dispatch:
  push:
    branches:
      - "${{ github.event.repository.default_branch }}"

jobs:
  release_helper:
    container:
      image: woodpeckerci/plugin-ready-release-go
      env:
        PLUGIN_RELEASE_BRANCH: "${{ github.event.repository.default_branch }}"
        CI_FORGE_TYPE: github
        PLUGIN_GIT_EMAIL: patrick.schratz@gmail.com
        PLUGIN_GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

